version: "3"
services:
  web:
    image: rothgyr/lolz:hello-world-app
    deploy: 
      replicas: 5
      resources: 
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports: 
      - "4000:80"
    netowrks:
      - webnet
networks:
  webnet:
